### ISSUE TITLE
Connect GCP to the logs

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#647]
Connect GCP Logging with the actual docker container. This will allow easier Monitoring + Optional notifications if needed.
https://docs.docker.com/config/containers/logging/gcplogs/ 

docker-compose.yml

```yaml
version: '3'
services:
  <service-name>:
    logging:
      driver: gcplogs
```
